<?php

namespace App\Libraries\SEO;

use App\Models\SettingModel;

/**
 * robots.txt generation from site settings (PRD ADDENDUM §7). Regenerated
 * whenever admin settings are saved and on `php spark db:seed`.
 */
class RobotsTxtGenerator
{
    public function __construct(protected ?SettingModel $settings = null)
    {
        $this->settings ??= new SettingModel();
    }

    public function generate(): string
    {
        $lines = [
            '# Auto-generated by LightCMS — do not edit by hand,',
            '# it will be overwritten on the next settings save.',
            '# Last updated: ' . date('Y-m-d H:i:s'),
            '',
            'User-agent: *',
        ];

        $allowIndex = (string) $this->settings->get('robots_index', '1') === '1';
        $lines[]    = $allowIndex ? 'Allow: /' : 'Disallow: /';
        $lines[]    = '';
        $lines[]    = '# Admin & system paths';
        $lines[]    = 'Disallow: /admin/';
        $lines[]    = 'Disallow: /writable/';

        $crawlDelay = $this->settings->get('robots_crawl_delay');

        if ($crawlDelay) {
            $lines[] = '';
            $lines[] = "Crawl-delay: {$crawlDelay}";
        }

        $lines[] = '';
        $lines[] = 'Sitemap: ' . base_url('sitemap.xml');

        return implode("\n", $lines) . "\n";
    }

    public function write(): string
    {
        $content = $this->generate();
        file_put_contents(FCPATH . 'robots.txt', $content);

        return $content;
    }
}
